name: Publish Package @vinybergamo/pagarme

on:
  release:
    types: [created]
    branches:
      - pagarme

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: yarn build:pagarme

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - run: yarn build:pagarme
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
